<?php

/**
 * @var \User\Model\User $user
 * @var int              $id
 */

$title = 'Delete user';
$url   = $this->url('user', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($user->firstName) ?> <?= $this->escapeHtml($user->lastName) ?> <?= $this->escapeHtml($user->patronymic) ?>
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $user->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>