<?php

/**
 * @var \User\Form\UserForm $form
 * @var int                 $id
 */

$title = 'Edit user';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$firstName = $form->get('first_name');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', 'First name');

$lastName = $form->get('last_name');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', 'Last name');

$patronymic = $form->get('patronymic');
$patronymic->setAttribute('class', 'form-control');
$patronymic->setAttribute('placeholder', 'Patronymic');

$birthDate = $form->get('birth_date');
$birthDate->setAttribute('class', 'form-control');
$birthDate->setAttribute('placeholder', 'yyyy-mm-dd');

$city = $form->get('city_id');
$city->setAttribute('class', 'form-control');
$city->setAttribute('placeholder', 'Native city');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($firstName) ?>
        <?= $this->formElement($firstName) ?>
        <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($lastName) ?>
        <?= $this->formElement($lastName) ?>
        <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($patronymic) ?>
        <?= $this->formElement($patronymic) ?>
        <?= $this->formElementErrors()->render($patronymic, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($birthDate) ?>
        <?= $this->formElement($birthDate) ?>
        <?= $this->formElementErrors()->render($birthDate, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($city) ?>
        <?= $this->formElement($city) ?>
        <?= $this->formElementErrors()->render($city, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();